name: EAS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      # Setup Expo and EAS
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKE }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Trigger Android APK build
      - name: Build APK
        run: eas build --platform android --non-interactive

      # Upload APK to Artifacts (optional)
      - name: Upload APK to Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: expo-android-apk
          path: dist/*.apk
